name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - ".github/workflows/test.yml"
      - "Makefile"

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.38.x"
        host_version:
          - vim: "v9.0.1499"
            nvim: "v0.8.0"
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
        with:
          path: "./repo"
      - uses: actions/checkout@v4
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"
      - name: Check Path
        id: path
        run: |
          echo "vim-home=$HOME/vim-$VIM_VER" >> $GITHUB_OUTPUT
          echo "vim-executable=$HOME/vim-$VIM_VER/bin/vim" >> $GITHUB_OUTPUT
        env:
          VIM_VER: ${{ matrix.host_version.vim }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: "${{ matrix.host_version.vim }}"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
          ${DENOPS_TEST_VIM} --version
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable }}
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
          ${DENOPS_TEST_NVIM} --version
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable }}
      - run: |
          "${DENOPS_TEST_VIM_EXECUTABLE}" -u NONE -i NONE -n -N -X -e -s -V1 -c visual -c "echomsg 'foo'" -c "call timer_start(3000, {-> execute('quit!')})" -c "sleep 1" -c "echomsg 'bar'"
        env:
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
      - name: Test
        run: deno test -A with_test.ts
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
          DENOPS_TEST_VERBOSE: 1
        working-directory: ./repo
