name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - ".github/workflows/test.yml"
      - "Makefile"

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
        version:
          - "1.x"
        host_version:
          - vim: "v9.0.1499"
            nvim: "v0.8.0"
        include:
          - runner: ubuntu-latest
            cache: true
          - runner: macos-latest
            cache: true
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
        with:
          path: "./repo"
      - uses: actions/checkout@v4
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"
      - name: Check Path
        id: path
        run: |
          echo "vim-home=$HOME/vim-$VIM_VER" >> $GITHUB_OUTPUT
          echo "vim-executable=$HOME/vim-$VIM_VER/bin/vim" >> $GITHUB_OUTPUT
        env:
          VIM_VER: ${{ matrix.host_version.vim }}
      - uses: actions/cache@v4
        id: cache
        if: matrix.cache
        with:
          key: vim-${{ runner.os }}-${{ matrix.host_version.vim }}
          path: ${{ steps.path.outputs.vim-home }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - uses: rhysd/action-setup-vim@v1
        id: vim
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: "${{ matrix.host_version.vim }}"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
          ${DENOPS_TEST_VIM} --version
        env:
          DENOPS_TEST_VIM: ${{ steps.path.outputs.vim-executable }}
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
          ${DENOPS_TEST_NVIM} --version
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable }}
      - name: Test
        run: echo OK1
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.path.outputs.vim-executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
        working-directory: ./repo
